<Project>
  <PropertyGroup>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <ApplicationDisplayVersion>$(Version)</ApplicationDisplayVersion>
    <ApplicationVersion>$(Version)</ApplicationVersion>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'GenderNameEstimator.Tools' And Exists('$(MSBuildThisFileDirectory)appsettings.Secrets.json')">
    <EmbeddedResource Include="$(MSBuildThisFileDirectory)appsettings.Secrets.json"
                      LogicalName="GnE.appsettings.Secrets.json" />
  </ItemGroup>
</Project>
