<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>GenderNameEstimator.Tools.Tests</RootNamespace>
    <ReleaseVersion>1.0.2</ReleaseVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.14.0"><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
<PrivateAssets>all</PrivateAssets>
</PackageReference>
    <PackageReference Include="coverlet.collector" Version="10.0.1"><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
<PrivateAssets>all</PrivateAssets>
</PackageReference>
		<PackageReference Include="EPPlus" Version="8.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GenderNameEstimator.Tools\GenderNameEstimator.Tools.csproj" />
  </ItemGroup>
</Project>
